title = "boblog config"

temp_consumer_state = false

[web_config]
port = 8011

[[topics]]
name = "test-topic"
compression = true
cap = 100
cap_tolerance = 10
temporary = false
[[topics]]
name = "test-topic-stress"
compression = true
cap = 100
cap_tolerance = 10
temporary = false
[[topics]]
name = "test-topic-cap"
compression = true
cap = 10
cap_tolerance = 3
temporary = false
[[topics]]
name = "test-topic-backpressure"
compression = true
cap = 10
cap_tolerance = 3
temporary = false
backoff_dialation_ms = 1000
