name: Build and Publish Rust Binary Bob-ka

on:
  push:
    tags:
      - 'v*.*.*' 
      
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build release binary
        run: cargo build --release

      - name: Package binary
        run: |
          mkdir -p dist
          cp target/release/bob_ka dist/
          tar -czvf dist/bob_ka.tar.gz -C dist bob_ka

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/bob_ka.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
