name: Rust

on:
  push:
    branches: [ "main" ]
    tags:
      - "*.*.*"
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Package binary
      run: |
          mkdir -p dist
          cp target/release/bob_ka dist/
          tar -czvf dist/bob_ka.tar.gz -C dist bob_ka

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
          files: dist/bob_ka.tar.gz
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: test
      run: ./build_n_test.sh
