name: Run Integration Tests

on:
  push:
    branches:
      - '*'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Integration Tests
        run: ./build_n_test.sh
